### ISSUE TITLE
Bot functionality gradually slows down

### ISSUE THREAD

**Issue by jotslo** [ScriptersCF/Discord_Bot#2]
As the bot continues to run, specifically adding roles and changing nicknames start to take significantly longer than they would have done when the bot first started up.

The cause of the bug is currently unknown, so any ideas would be very much appreciated due to the effect this has on vital bot functionality.

**Comment by ZacBytes** [comment]
Could it be your hosting issue?

**Comment by jotslo** [comment]
> Could it be your hosting issue?

@ZacBytes The issue likely has nothing to do with the VPS used to host the bot, as I also run a public games bot without any similar issues.

**Comment by jotslo** [comment]
The issue has been identified and help is no longer needed. Automatic nickname renaming was causing rate limiting issues due to the use of unusual characters in nicknames and the bot interpreting it incorrectly.
